### ISSUE TITLE
net::ERR_CONNECTION_REFUSED seen on Android for card payment & saving card

### ISSUE THREAD

**Issue by Vasant-Patel** [Nets-mobile-acceptance/Netaxept-Android-SDK#57] opened 2022-05-23 09:51 UTC
Hi,

Some of our customer are seeing the issue on Android when paying with card or saving a card and performing SCA flow. It seems once they authorize the redirection fails with net::ERR_CONNECTION_REFUSED on SDK side

We are using localhost as our host for redirectUrl and while it works for most users we are seeing some complains from Android users where final redirection seems to fail with ERR_CONNECTION_REFUSED

We have seen similar redirection issues on Android webview in other context where detecting redirection based on some url fails with ERR_CONNECTION_REFUSED as webview doesn't stop loading 

Case:
Android  9 (api version 28)
samsung Galaxy A7 (SM-A750FN)

![err_connection_refused](https://user-images.githubusercontent.com/8254593/169793540-18325b87-6860-456f-86ac-278eb114c6d2.png)
![Screenshot_20220515-171049](https://user-images.githubusercontent.com/8254593/169801112-cb5117d7-ae76-4d2b-bdbd-7faf39be9f02.jpg)

**Comment by Miss-PiA** [comment] 2022-05-24 07:29
Hi @Vasant-Patel 
Please provide the following details so that we have a better understanding of the issue

- Version of SDK
- Steps to reproduce issue the issue

**Comment by Miss-PiA** [comment] 2022-06-13 08:11
Hi @Vasant-Patel are you still facing this issue or it has been resolved on your end?
If it is resolved, is it safe to close this issue?

**Comment by Vasant-Patel** [comment] 2022-06-22 09:17
Hi, Apologies for late reply

Its difficult to reproduce this issue but the issue has been seen with Android SDK version 2.2.0

**Comment by BuildManager-Nets** [comment] 2022-06-27 04:53
Hi 
It seems like you are trying to access “localhost” which is usually device’s local server but “localhost” is not recognizable by WebView that’s why you are getting that error.
Request you to please try the valid URL

**Comment by Miss-PiA** [comment] 2022-07-21 05:40
Hi

Is the issue resolved at your end? And is it okay to close this issue?

**Comment by Miss-PiA** [comment] 2022-08-04 07:58
Closing this issue because of no activity in a long time. Please feel free to reopen the issue, if you face problem regarding the same issue.

**Closed by Miss-PiA** 2022-08-04 07:58 UTC
